### ISSUE TITLE
getUserPlaylists issue with undefined userId

### ISSUE THREAD

**Issue by neilime** [JMPerez/spotify-web-api-js#135]
I need to retrieve the first 50 playlists of current user.

Typescript definition of function getUserPlaylists : 
`getUserPlaylists(userId?: string, options?: Object,...` suggest to do :
`getUserPlaylists(undefined, {limit: 50});`

I does not work...

Actually the function `getUserPlaylists` does not work as expected according to the doc and typescript typing.

If the userId is not a string (undefined or anything else), the first argument become the options.

But in typescript you cannot pass an object as the first argument because it must be a string or undefined.

**Comment by EricLambrecht** [comment]
I had the same issue! Since I don't use Typescript I was able to just use the first parameter as options, but my IDE is not happy of course. And for me it was very confusing figuring out why it didn't work initially.

**Comment by mzbrandl** [comment]
I faced the same issue. A workaround is adding `// @ts-ignore` before the function call.

**Comment by emyann** [comment]
I had the same issue, and I dug a bit in the source. Here's what I found if it could help:

- When calling `getUserPlaylists(undefined, { limit: 20 })` with userId as undefined, the `options` get replace with `userId` and `options` are forwarded to callback https://github.com/JMPerez/spotify-web-api-js/blob/b0c0143c961c5ebed699a450471ad47820e64ed2/src/spotify-web-api.js#L676-L690
- Then `_checkParamsAndPerformRequest ` is called with `_checkParamsAndPerformRequest(requestData, undefined, { limit: 20 })`, and it turns out the `options` and the `callback` are removed from the request
https://github.com/JMPerez/spotify-web-api-js/blob/b0c0143c961c5ebed699a450471ad47820e64ed2/src/spotify-web-api.js#L143-L162

I got around this issue by requesting the `userId` and calling `getUserPlaylists(undefuserIdined, { limit: 20 })` instead.
