### ISSUE TITLE
Add support for reordering tracks in a playlist

### ISSUE THREAD

**Issue by JMPerez** [JMPerez/spotify-web-api-js#17]
See the recently released endpoint https://developer.spotify.com/web-api/reorder-playlists-tracks/

**Comment by zzarcon** [comment]
@JMPerez the method it's already implement [here](https://github.com/JMPerez/spotify-web-api-js/blob/master/src/spotify-web-api.js#L641-L652), so maybe you can close the PR, right?

**Comment by JMPerez** [comment]
True, it's already implemented :)

**Comment by zzarcon** [comment]
Haha Sorry for the spam!, but I started implementing the method and just see that was already done :).

BTW do you have in mind some missing feature for the lib? I was thinking about provide some login mechanism instead of only setting the token directly. What do you think?

Mmm maybe this is not the right way for discuss that, but... :dancers:
