### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by ryqndev** [JMPerez/spotify-web-api-js#188]
**Describe the bug**
Documentation site is down

**To Reproduce**
1. open [https://doxdox.org/jmperez/spotify-web-api-js](https://doxdox.org/jmperez/spotify-web-api-js)
2. See error

**Screenshots**
![Screen Shot 2020-11-14 at 1 30 04 PM](https://user-images.githubusercontent.com/8120855/99157424-8a6b7e00-267d-11eb-9cfc-1e1a6e85c3fd.png)

**Desktop (please complete the following information):**
 - Mac / Firefox 81.0.2 (64 bit)

**Comment by TomasCarlson** [comment]
For temporary use, I archived the Google Cache if anyone needs the documentation in the meantime:

https://web.archive.org/web/20201208164648/http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fdoxdox.org%2Fjmperez%2Fspotify-web-api-js

**Comment by JMPerez** [comment]
Thank you @ryqndev and @TomasCarlson. Not sure what happened with doxdox but it looks like the service is down.

I'll try to bring up some GH Pages to host the docs. The content for the docs still leaves in the code. Since I'm using JSDoc it's easy to see in the code the comments explaining what each function does.

It's not the best experience but at least it's something while I fixed the pubic docs.

**Comment by JMPerez** [comment]
This should be fixed now. Docs are deployed on https://jmperezperez.com/spotify-web-api-js/
