### ISSUE TITLE
Hi, how can I get album instead of tracks?

### ISSUE THREAD

**Issue by calixto111** [JMPerez/spotify-web-api-js#52]
Hi Jose Manuel , 
this website is using Spotify-web-api-js , how can I make it do albums instead of tracks?
for example , 
Michael Jackson - Off the Wall 
Off the Wall is an album and a track of the same album 
this website is giving me the track uri
spotify:track:3zYpRGnnoegSpt3SguSo3W
but I would like to get the album uri instead
spotify:album:2ZytN2cY4Zjrr9ukb2rqTP
How can I achieve this task?

thanks

**Comment by JMPerez** [comment]
Hi @calixto111. Not sure what website you are referring to, but it seems to be using [the search endpoint](https://developer.spotify.com/web-api/search-item/). You can pass "album" as the type of search results you want to get back, instead of "track".

Eg https://api.spotify.com/v1/search?q=Michael+Jackson+Off+the+Wall&type=album

You can also use the Web API console as a playground: https://developer.spotify.com/web-api/console/get-search-item?q=Michael+Jackson+Off+the+Wall&type=album

**Comment by calixto111** [comment]
hi , JMPerez,
this is the website I refered to 
http://michaeldick.me/YetAnotherSpotifyPlaylistConverter/
how can I edit this to get a different result , I mean album uri , instead of track?
thanks
