### ISSUE TITLE
Add the ability to set a refresh token

### ISSUE THREAD

**Issue by orangemooncreative** [JMPerez/spotify-web-api-js#63]
I am not sure if I am missing something...but I don't see an option to set a refresh token. I noticed that the node version offers that option. Considering that the spotify api requires authentication for all api access this would be great to have since the keys expire after an hour.

reference: https://github.com/thelinmichael/spotify-web-api-node

**Comment by igorPhelype** [comment]
I also notice that.
I think that the web-api-js cannot have it because it is impossible to set a refresh token in the client side.

**Comment by ntaylor89** [comment]
I'm fairly certain @igorPhelype is correct.

To make that request, you need send your `client_id` and `client_secret`. We don't want to expose those values in the front end because of security concerns. You can't retrieve a token from the front-end for the exact same reason.

**Comment by ntaylor89** [comment]
If you're building a front-end heavy/ single page app, one possible solution would be to have a back end microservice handle this auth stuff for you, and then pass your front end the access token.

**Comment by igorPhelype** [comment]
@orangemooncreative,
Take a look at this gist:
https://gist.github.com/igorPhelype/68239ecab9afcc50230ce0c61c3bac2f

And I did this simple webapp just for learning react, you can see the implementation:
https://github.com/igorPhelype/Spotigorfy

You can use my method, or follow @ntaylor89's recomendation, because I honestly think that my aproach is not that perfect.

**Comment by ntaylor89** [comment]
Nice. I also have been building a webapp that uses spotify to learn React.

Note that Spotify's API allows 3 authentication types (all from the OAuth2 standard)
1. Authorization Code flow
2. Client Credentials flow
3. Implicit Grant

The Authorization code flow has to happen in the backend. It will allow you to access a users data, and gives you a way of extending the token use after it expires.

The Client credentials flow still happens in the backend, but doesn't require users to login. This allows you to get faster API rates and access the public data not available without authentication. You can still get refresh tokens. But you can't access users data.

The Implicit grant flow happens in the front end. Users login and you can get access to their personal data. However, there is now way to extend the token. When it expires, they will have to login again.

That's why you see this limitation: It's dictated by Spotify (who is following the OAuth2 Standard). 

My guess is that you're using the implicit grant flow, so you can get the initial token from this repo, but you'll never be able to get a refresh token.

**Comment by ntaylor89** [comment]
If you need longer access to the api without re-authentication, then you'll need to either use the Authorization Code Flow or the Client Credentials Flow in the backend.

For my side-project, I need users to login, so I went the the Authorization Code flow. I've been working on a microservice to make this a bit easier: https://github.com/ntaylor89/micro-spotify

The idea is that you spin up that microservice on `now.sh`, point users to it for authentication, and you'll get back an access token. I still haven't implemented a refresh flow yet, but you can use it as an example of how to do auth in the back end.

**Comment by JMPerez** [comment]
Thank you very much everyone who helped supporting @orangemooncreative! As mentioned, this library is intended to be used client-side and it doesn't support refreshing the token. https://github.com/thelinmichael/spotify-web-api-node is the option for server-side token exchange if you are using node.

I'll close this ticket. Feel free to reopen it if there was something missing.

**Comment by kasperkamperman** [comment]
I came across this closed subject, because I had the same question. Still I need to get something clear. 

My current idea so to do the authorization flow (will use PHP for this) and in that way obtain an accessToken and refreshToken. 

Well that accessToken I can use of course within this wrapper, I was thinking to store it in sessionStorage. 

However why can't I store the refreshToken also in sessionStorage, and do a client site request to obtain a new assessToken? What is the added security risk in this case (suppose I use https and everything)? 

My work around would be to store the refreshToken in a PHP session and request a new token in that way. But I'm interested why it wouldn't be possible client side.

**Comment by djansen1987** [comment]
@kasperkamperman ever found the answer to that question ?

> I came across this closed subject, because I had the same question. Still I need to get something clear.
> 
> My current idea so to do the authorization flow (will use PHP for this) and in that way obtain an accessToken and refreshToken.
> 
> Well that accessToken I can use of course within this wrapper, I was thinking to store it in sessionStorage.
> 
> However why can't I store the refreshToken also in sessionStorage, and do a client site request to obtain a new assessToken? What is the added security risk in this case (suppose I use https and everything)?
> 
> My work around would be to store the refreshToken in a PHP session and request a new token in that way. But I'm interested why it wouldn't be possible client side.

**Comment by kasperkamperman** [comment]
I think you can do that indeed. I'm no security specialist. But with https
and other measures it wont harm I think.

**Comment by kasperkamperman** [comment]
If you want to do it secure, you could use a proxy. So run all the calls
over your own server, if the token is expired request a new one with the
refresh token you have stored server side. Im using the PHP spotify library.

https://github.com/jwilsson/spotify-web-api-php
