### ISSUE TITLE
changePlaylistDetails does not save description field

### ISSUE THREAD

**Issue by wdehoog** [JMPerez/spotify-web-api-js#99]
Eventhough the server responds OK, calling changePlaylistDetails does not save the description field.

**Comment by JMPerez** [comment]
@wdehoog Could you provide a test case that helps debugging this issue?

I have just tried it myself and it does change the description as expected:

```js
const a = new SpotifyWebApi();
a.setAccessToken('...');
a.changePlaylistDetails('jmperezperez', '05pgWAXWu8WYhm0k0qY5je', {
  name: 'A new name',
  description: 'A new description'
});
```

Alternatively, try your access token, playlist id and user id on https://developer.spotify.com/console/put-playlist/ to confirm it works there.

**Comment by wdehoog** [comment]
I just tried it on the console with 
```
{"collaborative":false,"name":"Test  123","public":true,"description":"Hello"}
```
 Same behaviour. But when I started Spotify desktop (windows) there the description is indeed changed/added. I was only looking in my app at the returned data from getUserPlaylists. Should it not be in there as well?

**Comment by JMPerez** [comment]
You mean that you make a second request to `getUserPlaylists()` and wasn't updated? What you could do instead is assume that if the request to change the data was successful you update your local data without making that additional request to Spotify.

In any case, this is not a problem in the library since it is passing the information correctly to Spotify, so I'm closing this issue. If you are getting stale data that is something that should be reported to Spotify on https://github.com/spotify/web-api/issues.

Regardless of it, it seems that the library is working and passing the information to Spotify. If it takes some
